### ISSUE TITLE
Part no compatible with Slic3r

### ISSUE THREAD

**Issue by alainm** [Intrinsically-Sublime/Tantillus#2]
The part `Tantillus / Laser cut case / Corners / Corner_top_front_left.stl` cannot be sliced with Slic3r.

I could successfully fix it with cloud.netfabb.com, but I believe that the fixed file could be replaced in this repository to make things simpler for everyone.

Of course it would be better still to fix the part to eliminate the problem. I had such a problem with OpenSCAD due to a subtraction of two cylinders that had a 0 width wall, I changed something to get 0.1mm width and it worked!

I opened a Slic3r issie here https://github.com/alexrj/Slic3r/issues/739

**Comment by Intrinsically-Sublime** [comment]
This is a common problem with STL's and something you will come across very often printing parts that were generated using boolean functions. It is true you can move a part a fraction of a mm and it may generate the part without the flaw but the movement of the part will show up on a high res printer when printed. This is not much of a problem when printing on most machines as they can not resolve 0.1mm but Tantillus can. It is best to just repair the file and use that version. If you fork the Tantillus repo and fix the file in your repo you can then send me a pull request and I can merge it with this repo.

**Comment by alainm** [comment]
For the time being I am puting my fixed files in here: https://www.dropbox.com/sh/vg6z62pi1io957p/DN0FxdH0TG/TantillusFixed

Sorry, but it's a work in progress, I haven't printed all the parts so far.
I have only Corners, Axis and Extruders, more to come...

**Comment by alranel** [comment]
Just an update: Slic3r now has automatic STL file repair, so the file works correctly.
