### ISSUE TITLE
Tantillus.org Website Down

### ISSUE THREAD

**Issue by Michael-Bell** [Intrinsically-Sublime/Tantillus#3]
Just displays a white page with a link to a [Privacy Policy](http://www.whoisprivacyprotect.com/terms/privacy.html). If you cannot pay for hosting, consider uploading the static html to Github Pages(Free) or AWS for pennies, and host any videos on Youtube for free. Otherwise, can you make a download of the website available on a site like Dropbox/Google Drive/OneDrive?

**Comment by WillAdams** [comment]
There seems to be a good archive on the Wayback machine: https://web.archive.org/web/*/http://www.tantillus.org

Is the design mature / stable enough for a book to be done on it?

If so, what licensing terms would be appropriate? GPL, right? Would there be any interest in a collaboration? What terms would be appropriate for compensation for use of the GPL design in a book? Please contact me about this --- I'd like to write one which features the Tantillus (or some similar design).

Thanks.

**Comment by q2dg** [comment]
Eh, what's going on??
This thing seems pretty abandoned...
